services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8001:8001"
    env_file:
      - ./auth-service/.env

    restart: always

  job-service:
    build:
      context: ./job-service
      dockerfile: Dockerfile
    container_name: job-service
    ports:
      - "8002:8002"
    env_file:
      - ./job-service/.env

    restart: always

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    ports:
      - "8003:8003"
    env_file:
      - ./notification-service/.env

    restart: always

  application-service:
    build:
      context: ./application-service
      dockerfile: Dockerfile
    container_name: application-service
    ports:
      - "8004:8004"
    env_file:
      - ./application-service/.env

    restart: always

  nginx-proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - auth-service
      - job-service
      - notification-service
      - application-service
    restart: always
