export const allCategories = [
  "Software Development",
  "Data Science",
  "Design",
  "Marketing",
  "Sales",
  "Customer Support",
  "Human Resources",
  "Finance",
  "Operations",
  "Product Management",
  "Quality Assurance",
  "DevOps",
  "Education",
  "Healthcare",
  "Legal",
  "Engineering",
  "Writing & Content",
  "Business Development",
  "Project Management",
  "Administration",
  "Manufacturing",
  "Retail",
  "Consulting",
  "Security",
  "Research & Development",
];
