name: Deploy on QA

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  deploy_on_qa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Generate deployment package
        run: |
          zip -r deploy.zip . -x '*.git'
      # - name: Deploy on Elastic beanstalk QA Env
      #   uses: einaregilsson/beanstalk-deploy@v22
      #   with: 
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     application_name: WorkHive
      #     environment_name: WorkHive-env
      #     version_label: "ver-${{ github.sha }}"
      #     region: ap-south-1
      #     deployment_package: deploy.zip 
