# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Continuous Integration

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Test Auth Service
        working-directory: ./auth-service
        run: |
          npm ci
          npm test
      - name: Test Job Service
        working-directory: ./job-service
        run: |
          npm ci
          npm test
      - name: Test Application Service
        working-directory: ./application-service
        run: |
          npm ci
          npm test
      - name: Test Notification Service
        working-directory: ./notification-service
        run: |
          npm ci
          npm test
