name: Keep Render Services Awake

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - https://workhive-auth-service.onrender.com/api/v2/auth/health
          - https://workhive-job-service.onrender.com/api/v2/jobs/health
          - https://workhive-notification-service.onrender.com/api/v2/notifications/health
          - https://workhive-application-service.onrender.com/api/v2/applications/health
          - https://workhive-proxy-service.onrender.com/api/v2/auth/health
    steps:
      - name: Ping ${{ matrix.service }}
        run: curl -s --fail ${{ matrix.service }}
